### ISSUE TITLE
Incorrect plugin id in Readme usage section 

### ISSUE THREAD

**Issue by cdsap** [eBay/metrics-for-develocity-plugin#35]
Following:
https://github.com/eBay/metrics-for-develocity-plugin?tab=readme-ov-file#usage
To include the plugin in the project README says:
```
plugins {
    id("com.gradle.metrics-for-develocity") version("<current version goes here>")
}
```

### Expected Behavior
It should  point to the correct plugin id `id("com.ebay.metrics-for-develocity")`

**Comment by mcumings** [comment]
🤦
